### ISSUE TITLE
error importing SFL files for SCOPE_7_DLM cruise

### ISSUE THREAD

**Issue by ctberthiaume** [uwescience/popcycle#38]
Looks like an error parsing dates in the SCOPE 7 DLM cruise SFL files. Stack trace:

```
Traceback (most recent call last):

  File "import_sfl.py", line 172, in <module>

    insert_all_files(args.db, args.evt_dir, args.cruise)

  File "import_sfl.py", line 127, in insert_all_files

    insert_files_bulk(find_sfl_files(evt_path), dbpath, cruise)

  File "import_sfl.py", line 106, in insert_files_bulk

    fix_and_insert_sfl(data, header, dbpath, cruise)

  File "import_sfl.py", line 73, in fix_and_insert_sfl

    if (dbcolumn_to_fixed_data[DATE][-3] != ":"):

KeyError: 'DATE'
```

**Comment by ctberthiaume** [comment]
This was the first cruise where SFL file names contained non-UTC timestamps, which was unexpected. import_sfl.py now supports any timezone in SFL file name timestamps.
